name: mfb
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  country_picker: ^2.0.19
  provider: ^6.0.5
  modal_progress_hud_nsn: ^0.3.0
  firebase_storage: ^11.0.14

  carousel_slider: ^4.2.1

  smooth_page_indicator: ^1.0.1
  shared_preferences: ^2.0.17

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.4.3
  image_picker: ^0.8.6+4
  searchbar_animation: ^0.0.4
  favorite_button: ^0.0.4
  easy_image_viewer: ^1.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  animated_floating_buttons: ^0.0.2
  file_picker: ^5.2.5
  video_player: ^2.6.0

  mime: ^1.0.4
  sizer: ^2.0.15
  image_cropper: ^3.0.1
  image: ^4.0.15
  flick_video_player: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
